// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaleAirTickets.DataContext;

#nullable disable

namespace SaleAirTickets.Migrations
{
    [DbContext(typeof(FlightContext))]
    partial class FlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaleAirTickets.Models.Airplane", b =>
                {
                    b.Property<int>("AirplaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirplaneId"));

                    b.Property<string>("AirplaneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AirplaneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirplaneId");

                    b.ToTable("Airplanes");

                    b.HasData(
                        new
                        {
                            AirplaneId = 1,
                            AirplaneNumber = "ABS123",
                            AirplaneType = "A380"
                        },
                        new
                        {
                            AirplaneId = 2,
                            AirplaneNumber = "JUR543",
                            AirplaneType = "A380"
                        },
                        new
                        {
                            AirplaneId = 3,
                            AirplaneNumber = "OPW235",
                            AirplaneType = "A380"
                        });
                });

            modelBuilder.Entity("SaleAirTickets.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("FlightId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SaleAirTickets.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Country = "Россия",
                            Name = "Санкт-Петербург"
                        },
                        new
                        {
                            CityId = 2,
                            Country = "Россия",
                            Name = "Москва"
                        },
                        new
                        {
                            CityId = 3,
                            Country = "Россия",
                            Name = "Уфа"
                        },
                        new
                        {
                            CityId = 4,
                            Country = "Турция",
                            Name = "Анталья"
                        },
                        new
                        {
                            CityId = 5,
                            Country = "Россия",
                            Name = "Краснодар"
                        },
                        new
                        {
                            CityId = 6,
                            Country = "Россия",
                            Name = "Тольяти"
                        },
                        new
                        {
                            CityId = 7,
                            Country = "Россия",
                            Name = "Казань"
                        },
                        new
                        {
                            CityId = 8,
                            Country = "Турция",
                            Name = "Стамбул"
                        },
                        new
                        {
                            CityId = 9,
                            Country = "Белоруссия",
                            Name = "Минск"
                        },
                        new
                        {
                            CityId = 10,
                            Country = "ОАЭ",
                            Name = "Абу-Даби"
                        });
                });

            modelBuilder.Entity("SaleAirTickets.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("ArrivalCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuisnessClassPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DepartureCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EconomyClassPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FlightId");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("ArrivalCityId");

                    b.HasIndex("DepartureCityId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AirplaneId = 2,
                            ArrivalCityId = 3,
                            ArrivalDate = new DateTime(2024, 7, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            BuisnessClassPrice = 20000m,
                            DepartureCityId = 1,
                            DepartureDate = new DateTime(2024, 7, 15, 5, 30, 0, 0, DateTimeKind.Unspecified),
                            EconomyClassPrice = 9000m
                        },
                        new
                        {
                            FlightId = 2,
                            AirplaneId = 1,
                            ArrivalCityId = 5,
                            ArrivalDate = new DateTime(2024, 7, 24, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            BuisnessClassPrice = 52000m,
                            DepartureCityId = 4,
                            DepartureDate = new DateTime(2024, 7, 24, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            EconomyClassPrice = 17000m
                        },
                        new
                        {
                            FlightId = 3,
                            AirplaneId = 3,
                            ArrivalCityId = 2,
                            ArrivalDate = new DateTime(2024, 7, 1, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            BuisnessClassPrice = 35000m,
                            DepartureCityId = 1,
                            DepartureDate = new DateTime(2024, 7, 1, 4, 30, 0, 0, DateTimeKind.Unspecified),
                            EconomyClassPrice = 13000m
                        },
                        new
                        {
                            FlightId = 4,
                            AirplaneId = 1,
                            ArrivalCityId = 7,
                            ArrivalDate = new DateTime(2024, 7, 1, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            BuisnessClassPrice = 25000m,
                            DepartureCityId = 3,
                            DepartureDate = new DateTime(2024, 7, 1, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            EconomyClassPrice = 11000m
                        },
                        new
                        {
                            FlightId = 5,
                            AirplaneId = 3,
                            ArrivalCityId = 3,
                            ArrivalDate = new DateTime(2024, 7, 15, 13, 55, 0, 0, DateTimeKind.Unspecified),
                            BuisnessClassPrice = 42000m,
                            DepartureCityId = 1,
                            DepartureDate = new DateTime(2024, 7, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            EconomyClassPrice = 14000m
                        });
                });

            modelBuilder.Entity("SaleAirTickets.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SaleAirTickets.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            ClassType = "Business",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = 2,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = 3,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = 4,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = 5,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = 6,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 6
                        },
                        new
                        {
                            SeatId = 7,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 7
                        },
                        new
                        {
                            SeatId = 8,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 8
                        },
                        new
                        {
                            SeatId = 9,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 9
                        },
                        new
                        {
                            SeatId = 10,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 10
                        },
                        new
                        {
                            SeatId = 11,
                            ClassType = "Business",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 11
                        },
                        new
                        {
                            SeatId = 12,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 12
                        },
                        new
                        {
                            SeatId = 13,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 13
                        },
                        new
                        {
                            SeatId = 14,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 14
                        },
                        new
                        {
                            SeatId = 15,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 15
                        },
                        new
                        {
                            SeatId = 16,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 16
                        },
                        new
                        {
                            SeatId = 17,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 17
                        },
                        new
                        {
                            SeatId = 18,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 18
                        },
                        new
                        {
                            SeatId = 19,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 19
                        },
                        new
                        {
                            SeatId = 20,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 20
                        },
                        new
                        {
                            SeatId = 21,
                            ClassType = "Business",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 21
                        },
                        new
                        {
                            SeatId = 22,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 22
                        },
                        new
                        {
                            SeatId = 23,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 23
                        },
                        new
                        {
                            SeatId = 24,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 24
                        },
                        new
                        {
                            SeatId = 25,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 25
                        },
                        new
                        {
                            SeatId = 26,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 26
                        },
                        new
                        {
                            SeatId = 27,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 27
                        },
                        new
                        {
                            SeatId = 28,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 28
                        },
                        new
                        {
                            SeatId = 29,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 29
                        },
                        new
                        {
                            SeatId = 30,
                            ClassType = "Economy",
                            FlightId = 1,
                            IsAvailable = true,
                            SeatNumber = 30
                        },
                        new
                        {
                            SeatId = 31,
                            ClassType = "Business",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = 32,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = 33,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = 34,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = 35,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = 36,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 6
                        },
                        new
                        {
                            SeatId = 37,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 7
                        },
                        new
                        {
                            SeatId = 38,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 8
                        },
                        new
                        {
                            SeatId = 39,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 9
                        },
                        new
                        {
                            SeatId = 40,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 10
                        },
                        new
                        {
                            SeatId = 41,
                            ClassType = "Business",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 11
                        },
                        new
                        {
                            SeatId = 42,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 12
                        },
                        new
                        {
                            SeatId = 43,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 13
                        },
                        new
                        {
                            SeatId = 44,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 14
                        },
                        new
                        {
                            SeatId = 45,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 15
                        },
                        new
                        {
                            SeatId = 46,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 16
                        },
                        new
                        {
                            SeatId = 47,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 17
                        },
                        new
                        {
                            SeatId = 48,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 18
                        },
                        new
                        {
                            SeatId = 49,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 19
                        },
                        new
                        {
                            SeatId = 50,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 20
                        },
                        new
                        {
                            SeatId = 51,
                            ClassType = "Business",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 21
                        },
                        new
                        {
                            SeatId = 52,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 22
                        },
                        new
                        {
                            SeatId = 53,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 23
                        },
                        new
                        {
                            SeatId = 54,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 24
                        },
                        new
                        {
                            SeatId = 55,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 25
                        },
                        new
                        {
                            SeatId = 56,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 26
                        },
                        new
                        {
                            SeatId = 57,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 27
                        },
                        new
                        {
                            SeatId = 58,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 28
                        },
                        new
                        {
                            SeatId = 59,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 29
                        },
                        new
                        {
                            SeatId = 60,
                            ClassType = "Economy",
                            FlightId = 2,
                            IsAvailable = true,
                            SeatNumber = 30
                        },
                        new
                        {
                            SeatId = 61,
                            ClassType = "Business",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = 62,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = 63,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = 64,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = 65,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = 66,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 6
                        },
                        new
                        {
                            SeatId = 67,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 7
                        },
                        new
                        {
                            SeatId = 68,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 8
                        },
                        new
                        {
                            SeatId = 69,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 9
                        },
                        new
                        {
                            SeatId = 70,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 10
                        },
                        new
                        {
                            SeatId = 71,
                            ClassType = "Business",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 11
                        },
                        new
                        {
                            SeatId = 72,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 12
                        },
                        new
                        {
                            SeatId = 73,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 13
                        },
                        new
                        {
                            SeatId = 74,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 14
                        },
                        new
                        {
                            SeatId = 75,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 15
                        },
                        new
                        {
                            SeatId = 76,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 16
                        },
                        new
                        {
                            SeatId = 77,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 17
                        },
                        new
                        {
                            SeatId = 78,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 18
                        },
                        new
                        {
                            SeatId = 79,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 19
                        },
                        new
                        {
                            SeatId = 80,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 20
                        },
                        new
                        {
                            SeatId = 81,
                            ClassType = "Business",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 21
                        },
                        new
                        {
                            SeatId = 82,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 22
                        },
                        new
                        {
                            SeatId = 83,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 23
                        },
                        new
                        {
                            SeatId = 84,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 24
                        },
                        new
                        {
                            SeatId = 85,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 25
                        },
                        new
                        {
                            SeatId = 86,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 26
                        },
                        new
                        {
                            SeatId = 87,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 27
                        },
                        new
                        {
                            SeatId = 88,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 28
                        },
                        new
                        {
                            SeatId = 89,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 29
                        },
                        new
                        {
                            SeatId = 90,
                            ClassType = "Economy",
                            FlightId = 3,
                            IsAvailable = true,
                            SeatNumber = 30
                        },
                        new
                        {
                            SeatId = 91,
                            ClassType = "Business",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = 92,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = 93,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = 94,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = 95,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = 96,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 6
                        },
                        new
                        {
                            SeatId = 97,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 7
                        },
                        new
                        {
                            SeatId = 98,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 8
                        },
                        new
                        {
                            SeatId = 99,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 9
                        },
                        new
                        {
                            SeatId = 100,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 10
                        },
                        new
                        {
                            SeatId = 101,
                            ClassType = "Business",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 11
                        },
                        new
                        {
                            SeatId = 102,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 12
                        },
                        new
                        {
                            SeatId = 103,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 13
                        },
                        new
                        {
                            SeatId = 104,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 14
                        },
                        new
                        {
                            SeatId = 105,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 15
                        },
                        new
                        {
                            SeatId = 106,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 16
                        },
                        new
                        {
                            SeatId = 107,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 17
                        },
                        new
                        {
                            SeatId = 108,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 18
                        },
                        new
                        {
                            SeatId = 109,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 19
                        },
                        new
                        {
                            SeatId = 110,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 20
                        },
                        new
                        {
                            SeatId = 111,
                            ClassType = "Business",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 21
                        },
                        new
                        {
                            SeatId = 112,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 22
                        },
                        new
                        {
                            SeatId = 113,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 23
                        },
                        new
                        {
                            SeatId = 114,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 24
                        },
                        new
                        {
                            SeatId = 115,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 25
                        },
                        new
                        {
                            SeatId = 116,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 26
                        },
                        new
                        {
                            SeatId = 117,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 27
                        },
                        new
                        {
                            SeatId = 118,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 28
                        },
                        new
                        {
                            SeatId = 119,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 29
                        },
                        new
                        {
                            SeatId = 120,
                            ClassType = "Economy",
                            FlightId = 4,
                            IsAvailable = true,
                            SeatNumber = 30
                        },
                        new
                        {
                            SeatId = 121,
                            ClassType = "Business",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 1
                        },
                        new
                        {
                            SeatId = 122,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 2
                        },
                        new
                        {
                            SeatId = 123,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 3
                        },
                        new
                        {
                            SeatId = 124,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 4
                        },
                        new
                        {
                            SeatId = 125,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 5
                        },
                        new
                        {
                            SeatId = 126,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 6
                        },
                        new
                        {
                            SeatId = 127,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 7
                        },
                        new
                        {
                            SeatId = 128,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 8
                        },
                        new
                        {
                            SeatId = 129,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 9
                        },
                        new
                        {
                            SeatId = 130,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 10
                        },
                        new
                        {
                            SeatId = 131,
                            ClassType = "Business",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 11
                        },
                        new
                        {
                            SeatId = 132,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 12
                        },
                        new
                        {
                            SeatId = 133,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 13
                        },
                        new
                        {
                            SeatId = 134,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 14
                        },
                        new
                        {
                            SeatId = 135,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 15
                        },
                        new
                        {
                            SeatId = 136,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 16
                        },
                        new
                        {
                            SeatId = 137,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 17
                        },
                        new
                        {
                            SeatId = 138,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 18
                        },
                        new
                        {
                            SeatId = 139,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 19
                        },
                        new
                        {
                            SeatId = 140,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 20
                        },
                        new
                        {
                            SeatId = 141,
                            ClassType = "Business",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 21
                        },
                        new
                        {
                            SeatId = 142,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 22
                        },
                        new
                        {
                            SeatId = 143,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 23
                        },
                        new
                        {
                            SeatId = 144,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 24
                        },
                        new
                        {
                            SeatId = 145,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 25
                        },
                        new
                        {
                            SeatId = 146,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 26
                        },
                        new
                        {
                            SeatId = 147,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 27
                        },
                        new
                        {
                            SeatId = 148,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 28
                        },
                        new
                        {
                            SeatId = 149,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 29
                        },
                        new
                        {
                            SeatId = 150,
                            ClassType = "Economy",
                            FlightId = 5,
                            IsAvailable = true,
                            SeatNumber = 30
                        });
                });

            modelBuilder.Entity("SaleAirTickets.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SaleAirTickets.Models.Booking", b =>
                {
                    b.HasOne("SaleAirTickets.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleAirTickets.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaleAirTickets.Models.Flight", b =>
                {
                    b.HasOne("SaleAirTickets.Models.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleAirTickets.Models.City", "ArrivalCity")
                        .WithMany()
                        .HasForeignKey("ArrivalCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleAirTickets.Models.City", "DepartureCity")
                        .WithMany()
                        .HasForeignKey("DepartureCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("ArrivalCity");

                    b.Navigation("DepartureCity");
                });

            modelBuilder.Entity("SaleAirTickets.Models.Payment", b =>
                {
                    b.HasOne("SaleAirTickets.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("SaleAirTickets.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SaleAirTickets.Models.Seat", b =>
                {
                    b.HasOne("SaleAirTickets.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("SaleAirTickets.Models.Booking", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
